### ISSUE TITLE
[Dev] Validación de address al enviar

### ISSUE THREAD

**Issue by jonallamas** [jonallamas/simple-wallet#2]
Al querer enviar cualquier token que el usuario posea, se puede pegar en el modal la _address_ desde el _clipboard_. Validar que al hacerlo ésta efectivamente sea una _address_

![Captura de Pantalla 2022-09-08 a la(s) 00 59 16](https://user-images.githubusercontent.com/25107314/189031251-a1efa1ef-268b-4782-9c77-435483351f30.png)

**Comment by joelalejandro** [comment]
Hablamos de una validación de frontend no? Algo al estilo regex?

**Comment by jonallamas** [comment]
> Hablamos de una validación de frontend no? Algo al estilo regex?

Nono, la idea es validarlo con la misma función interna de EthersJS: https://docs.ethers.io/v5/api/utils/address/#utils-isAddress

**Comment by jonallamas** [comment]
Cerrada en #44
